In [ ]:
!pip install Numpy

In [ ]:
import numpy as np


In [ ]:
list=[1,2,3,4]

In [ ]:
type(list)

list

In [ ]:
arr=np.array(list)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.size

4

In [ ]:
z=np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#one -dimensional array
o=np.array([1,2,3,4])

In [ ]:
o

array([1, 2, 3, 4])

In [ ]:
o.ndim

1

In [ ]:
o.shape

(4,)

In [ ]:
# 2-D array
x = np.array([[1,2,3],[4,5,6],[7,8,9],[55,44,33]])

In [ ]:
x



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [55, 44, 33]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(4, 3)

In [ ]:
x = x.reshape(3,2,2)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 55],
        [44, 33]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 2)

In [ ]:
x=x.reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 55, 44, 33]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(3, 4)

Indexing

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr[1]

2

In [ ]:
arr[1]+arr[2]

5

In [ ]:
#Accessing 2D array

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
print("2 element in 1st dim", arr[0,1])

2 element in 1st dim 2


In [ ]:
print("5 element in 2st dim",arr[1,4])

5 element in 2st dim 10


In [ ]:
# l inspace linspace(start,end,no. of values between 0 and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#identity matrix

In [ ]:
x = np.eye(3)

In [ ]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x.shape

(3, 3)

In [ ]:
(3,3)

(3, 3)

In [ ]:
np.random.randint(0,10,20)

array([0, 3, 2, 0, 8, 8, 0, 2, 8, 6, 3, 4, 5, 8, 7, 8, 1, 1, 6, 9])

In [ ]:
np.random.rand(3,3)

array([[0.40282412, 0.95063849, 0.61618898],
       [0.20357668, 0.98494091, 0.17263939],
       [0.45393417, 0.04739199, 0.08197039]])

In [ ]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.max()

10

In [ ]:
arr.argmax()

9

In [ ]:
a=np.arange(0,11,2)

Slicing

In [ ]:
a

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a[1:2]

array([2])

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[0:1,0:2]

array([[1, 2]])

In [ ]:
x[0:1,0:3]

array([[1, 2, 3]])

In [ ]:
x[2:3,0:2]

array([[7, 8]])

In [ ]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()

In [ ]:
x

array([1, 2, 3, 4, 5])

create an array 5 *5 which should contain from 0 to 24

In [ ]:
z = arr.view()

In [ ]:
z

array([1, 2, 3, 4, 5])

In [ ]:
arr[1] = 45

In [ ]:
arr

array([ 1, 45,  3,  4,  5])

In [ ]:
z

array([ 1, 45,  3,  4,  5])